// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: meals.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addIngredientsToMeal = `-- name: AddIngredientsToMeal :exec
INSERT INTO meal_ingredients (meal_id, ingredient_id)
SELECT $1, unnest($2::UUID[])
`

type AddIngredientsToMealParams struct {
	MealID  uuid.UUID
	Column2 []uuid.UUID
}

func (q *Queries) AddIngredientsToMeal(ctx context.Context, arg AddIngredientsToMealParams) error {
	_, err := q.db.ExecContext(ctx, addIngredientsToMeal, arg.MealID, pq.Array(arg.Column2))
	return err
}

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (id, created_at, updated_at, name, user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, name, user_id
`

type CreateMealParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	UserID    uuid.UUID
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRowContext(ctx, createMeal,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.UserID,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.UserID,
	)
	return i, err
}
