// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Ingredient struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Calories  int32
	Name      string
	UserID    uuid.UUID
}

type User struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Email         string
	Password      string
	CalorieIntake int32
	BearersToken  string
}
